dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=1
  # https://github.com/AbsInt/CompCert/issues/234
  - EXTRA_OPAM=menhir.20180528

  # for CompCert: http://compcert.inria.fr/man/manual002.html
  - COMPILER="system"
  # Main test targets
  # get versions from: https://opam.ocaml.org/packages/coq/
  # Only use versions that CompCert can build with...
  matrix:
  - TEST_TARGET="8.6.1"
  - TEST_TARGET="8.7.2"
  - TEST_TARGET="8.8.0"

before_script:
  -  ./ci/keep_alive.sh &

install:
  - opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
  - eval $(opam config env)
  - opam config var root
  # this somehow fails the second time...
  - opam repo add coq-released http://coq.inria.fr/opam/released || true
  - opam install -y --verbose -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET} -y
  - opam install -y --verbose -j ${NJOBS} coq-mathcomp-ssreflect
  - opam install -y --verbose -j ${NJOBS} ocamlfind camlp5 ${EXTRA_OPAM} 


script:
  - eval $(opam config env)
  - opam config var root
  # Look at how Coq builds compcert for their test suite
  # https://github.com/coq/coq/blob/b67b8ab65448a63cb53517ab9dfccb3b4d541d77/dev/ci/ci-compcert.sh
  - cd lib/CompCert &&  ./configure x86_64-linux -ignore-coq-version && make; cd ../../
  - make -j ${NJOBS} -C lib/paco/src 
  - make -j ${NJOBS} -C src/
  - cd src && ./vellvm --test
