dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  # https://github.com/AbsInt/CompCert/issues/234
  - EXTRA_OPAM=menhir.20180528

  # for CompCert: http://compcert.inria.fr/man/manual002.html
  - COMPILER="4.06.1"
  # Main test targets
  # get versions from: https://opam.ocaml.org/packages/coq/
  # Only use versions that CompCert can build with...
  matrix:
  - TEST_TARGET="8.6.1"
  - TEST_TARGET="8.7.2"
  - TEST_TARGET="8.8.0"

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config var root
- opam repo add coq-released http://coq.inria.fr/opam/released
- opam install -y --verbose -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET}
- opam install -y --verbose -j ${NJOBS} coq-mathcomp-ssreflect
- opam install -y --verbose -j ${NJOBS} ocamlfind camlp5 ${EXTRA_OPAM} 

script:
- eval $(opam config env)
- opam config var root
- cd lib/CompCert &&  ./configure x86_64-linux && make -j; cd ../../
- make -j ${NJOBS} -C lib/paco/src 
- make -j ${NJOBS} -C src/
- cd src && ./vellvm --test
