dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - EXTRA_OPAM=menhir
  # system is == 4.02.3
  - COMPILER="system"
  # Main test targets
  matrix:
  - TEST_TARGET="v8.6"
  - TEST_TARGET="v8.7"
  - TEST_TARGET="v8.8"
  - TEST_TARGET="master"

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config var root
- opam install -j ${NJOBS} -y ocamlfind camlp5 ${EXTRA_OPAM}
- opam list
- git clone --depth 1 -b ${TEST_TARGET} https://github.com/coq/coq.git coq-${TEST_TARGET}
- cd coq-${TEST_TARGET}
- ./configure -native-compiler no -local -coqide no
- make -j ${NJOBS}
- cd -

script:
- export PATH=`pwd`/coq-${TEST_TARGET}/bin:$PATH
- cd lib/CompCert &&  ./configure x86_64-linux && make -j2  && cd ../../
- make -j ${NJOBS} -C lib/paco/src 
- echo 'Building vellvm...' && echo -en 'travis_fold:start:vellvm.build\\r'
- make -j ${NJOBS} -C src/
- echo 'Build successful...' && echo -en 'travis_fold:end:vellvm.build\\r'
- echo 'Running test suite...' && echo -en 'travis_fold:start:vellvm.test\\r'
- cd src && ./vellvm --test
- echo 'Done running test suite...' && echo -en 'travis_fold:end:vellvm.test\\r'
