dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - EXTRA_OPAM=menhir
  # system is == 4.02.3
  - COMPILER="system"
  # Main test targets
  matrix:
  - TEST_TARGET="8.6"
  - TEST_TARGET="8.7"
  - TEST_TARGET="8.8"

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config var root
- opam repo add coq-released http://coq.inria.fr/opam/released
- opam install -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET}
- opam install -j ${NJOBS} -y ocamlfind camlp5 ${EXTRA_OPAM} 

script:
- export PATH=`pwd`/coq-${TEST_TARGET}/bin:$PATH
- cd lib/CompCert &&  ./configure x86_64-linux && make -j; cd ../../
- make -j ${NJOBS} -C lib/paco/src 
- make -j ${NJOBS} -C src/
- cd src && ./vellvm --test
